# Generated by Django 5.2.9 on 2025-12-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
