# Generated by Django 5.2.9 on 2025-12-03 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
