# Generated by Django 5.2.8 on 2025-11-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='farm_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='lga',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
